spring: 
  config:
    import: data-config.yml

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML5
    cache: false #캐시를 사용하지 않음
      
  datasource: #DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${dataconfig.db-url}
    username: ${dataconfig.db-username}
    password: ${dataconfig.db-password}
    hikari: #커넥션풀 
      connection-timeout : 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size : 10 #최대 커넥션 개수 설정
      max-lifetime : 1800000   
      
  messages: #메시지
    basename: messages.user,messages.mg,messages.hd,messages.il,messages.he,messages.jw
    encoding: UTF-8
    
  devtools: #정적 자원(html, css, js) 수정 시 새로고침 없이 바로 적용
    livereload:
      enabled: true
    
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정 (정확히는 classpath에 있는 모든 파일)
      enabled: true
      
  servlet:
    multipart:
      max-file-size: 50MB #파일 한 개당 최대 사이즈
      max-request-size: 50MB #요청당 최대 파일 크기

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${dataconfig.kakao-id}
            client-secret: ${dataconfig.kakao-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname
            client-authentication-method: client_secret_post

          naver:
              client-id: ${dataconfig.naver-id}
              client-secret: ${dataconfig.naver-secret}
              redirect-uri: "{baseUrl}/login/oauth2/code/naver"
              authorization-grant-type: authorization_code
              client-name: Naver
              scope: nickname

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그 지정
  level:
    root: error
    '[kr.spring]': debug
    org:
      spring:
        security: info

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


