dataconfig:
  db-url: jdbc:oracle:thin:@211.238.142.200:1521:xe #211.238.142.200 
  db-username: fteam01 #user01 #fteam01
  db-password: f1234 #1234
  
  #google-mail-url: 
  #google-mail-password: 
  #kakao-id: 
  #kakao-secret: 
  #naver-id: 
  #naver-secret: 

  rememberme-key: hayden